keys:
  - &aryn age1tlqjcnshux6f3g0uvx47zj9nc470jphnrlhll3vmz762wadszpnq628lfc
  - &laptop age1spe90vghhlxl5ahu294d2w4mmgszy6szhz2kmls2aey0ugmgva2qap0qds
  - &sardonix age1kxeqex7s9lujp2u4ke09uy4ad8zf30w056xsmppzfdq324c7j5hs8g47zz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *aryn
          - *laptop
          - *sardonix
