[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd font"
style = "Regular"

[window]
padding = { x = 1, y = 1 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = true
